name: mjacksi_products
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.7
  intl: any
  file_picker: ^5.2.2
  riverpod_annotation: ^2.1.2
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.2.6
  build_runner: ^2.4.6
  custom_lint: ^0.5.2
  riverpod_lint: ^2.0.1

flutter:
  uses-material-design: true

  fonts:
      - family: Cairo
        fonts:
          - asset: assets/fonts/Cairo-Bold.ttf
            weight: 700
          - asset: assets/fonts/Cairo-Medium.ttf
            weight: 500
          - asset: assets/fonts/Cairo-Regular.ttf
            weight: 400
